kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cmas
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-cmas
  ports:
    - name: http
      protocol: TCP
      port: 8001
  type: ClusterIP
